language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements_dev.txt

script:
  - pytest

after_success:
  - coveralls

stages:
- test
- 'Bump Version'
- deploy

jobs:
  include:
    - stage: 'Bump Version'
      python: '3.7'
      script: skip
      after_success:
        - echo "Creating and pushing new build version to master"
        - bumpversion --verbose --allow-dirty build --message "[skip travis] Bumping version from {current_version} -> {new_version}"
        - git remote add origin-version https://${GH_TOKEN}@github.com/francisco-perez-sorrosal/chronologger.git > /dev/null 2>&1
        - git checkout -b bump_version
        - git --no-pager log --oneline -n 5
        - git push origin-version bump_version:master
        - echo "Sending coverage report..."

    - stage: deploy
      python: '3.8'
      install: skip  # no tests, no depedencies needed
      script: skip  # we're not running tests
      deploy:
        provider: pypi
        distributions: sdist bdist_wheel
        skip_upload_docs: true
        skip_cleanup: true
        server: https://test.pypi.org/legacy/
        user: __token__
        password:
          secure: "SY0b9vcUt233TbV4+EtfE7XH6BSKz5MXObkuZHG6pg0NSgW7b3WD4koJcaqDSQUu0EuQErirCSDNM8DpiSCTBxYsceo9zBimCle7W9PeEbPTI3i4TKKsUcPdA3HYyge3sSo6vZ+mHw0xNDqFLN36KSIOUQWEghtIdOlaCGa1/KDkBIDsMUmSUKHE4fujAriuxFFRzdAyFw5gzABcQ1N7P2mQYcxxxSQpmeqj2QYyHXXw4RNtzYqaot7QFcZ91VSKhrzSoyXlxNjt6YkO28ksDN6j7Mr3ZaLX3bshpu4LJk+wS319aXMSWVqPbWdgawEWQfABoBJKjMWb1lQkEeHl3jevYV3jAg2YF5od8zE+hew4BZPIuvc8pu/Z4UnMG/7/rAmqkBN8EFcUXMcQyc+RzWrrUQJ539RRmIXfMCS0fZEiCSiPhwplfc62a8QNNNsAUflWHD5xwKqaPQVYO+/EzVt+7zN6PLfFxDXLcmPU4YCY4pMylBvq4q9XV87JmAljrfwx8vKl2oXc4RMu6zXt4qQCBMtog5ISrb3+mBl8fHl+SXY/7oZp+c20cscmQfYbIiwSTKoFLEogZu5m8oxq1SIFJbjeU6v5+mvFXC6x28xW968nY90iqXuLa7MyVsB59fNvvzNm2usUS5VsJQZzoQP45mhqJ6d3nBuDr0WE+g8="
        on:
          tags: false
          repo: francisco-perez-sorrosal/chronologger
